name: Atualizar README.md

on:
  schedule:
    # runs once a week on sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Atualizar a README deste repositório com as atividades recentes

    steps:
      - uses: actions/checkout@v2
      - uses: guiga-zalu/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Últimas ações'
          MAX_LINES: 12
          LANG: 'pt-BR'